---
# Install SSL packages for Centos 6
- yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python-urllib3
    - pyOpenSSL
    - python-ndg_httpsclient
    - python2-pyasn1
  when: ansible_distribution_major_version|int < 7

# Install tasks
- include: install.yml

- debug:
    msg: "restart nginx"
  notify: nginx restart